spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    #    ;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  thymeleaf:
    check-template-location: false

  h2:
    console:
      enabled: true
      path: /h2-ui
      settings.trace: true
      settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false


  # swagger-ui custom path
#app:
#  auth:
#    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
#    tokenExpirationMsec: 8640000000
#    refreshTokenExpirationMsec: 172800000
#  cors:

springdoc:
  packages-to-scan: com.example.demo.controller
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
#  packages-to-exclude: com.example.demo.controller

#  paths-to-exclude: /error, /actuator/**
#    operations-sorter: alpha
#    tags-sorter: alpha
